### ISSUE TITLE
VUR

### ISSUE THREAD

**Issue by zen0bit** [shubham-cpp/void-pkg-templates#1]
I know, you do not intend to submit these..
but don't you wanna push them to my unofficial repo?
[VUR](https://github.com/oSoWoSo/VUR)

I wanna gather every templates posible to it.

Actually I am creating spin distribution with support to VUR included...

Cheers and happy voiding :+1:

**Comment by shubham-cpp** [comment]
I could do. The only issue is that my company has given me the laptop with fedora on it.
So I'm not using void anymore. What  I could do is install void on VM, test these packages and then make a PR.
How does that sound?
